name: Deploy Databricks Bundle
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy_bundle:
    name: Deploy Bundle
    runs-on: ubuntu-latest
    environment: prod
    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
      DATABRICKS_CLIENT_ID: ${{secrets.DATABRICKS_CLIENT_ID}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main
      
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Deploy
        run: databricks bundle deploy -t prod
